# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e18dee09c8cce277f7eae6192a86faf94f230f8d8029c26f5222f6bf19c33e2a06f9ae9f6d6131399b350e297ef6e2937936c2f1f803b707fc06f4aa7f024f5a

test:
  secret_key_base: 70f741dc2ad51dad60d2a119ede49f4918ff104c8fb38e2f18b7444df88dd62af8af1f425bab4cd67687a8e575db9ba3b4ab62348a5cc33519347937ae19111a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
